DROP TABLE IF EXISTS t_tinylog;
DROP TABLE IF EXISTS t_stripelog;
DROP TABLE IF EXISTS t_log;
DROP TABLE IF EXISTS t_memory;
DROP TABLE IF EXISTS t_set;
DROP TABLE IF EXISTS t_join_log;
DROP TABLE IF EXISTS t_join;
DROP TABLE IF EXISTS t_buffer_log;
DROP TABLE IF EXISTS t_buffer;
DROP TABLE IF EXISTS t_merge_mt;
DROP TABLE IF EXISTS t_merge_log;
DROP TABLE IF EXISTS t_merge;
DROP TABLE IF EXISTS t_null;
DROP TABLE IF EXISTS t_url;
DROP TABLE IF EXISTS t_generaterandom;
DROP TABLE IF EXISTS t_jdbc;
DROP TABLE IF EXISTS t_odbc;
DROP TABLE IF EXISTS t_mongodb;
DROP TABLE IF EXISTS t_postgresql;
DROP TABLE IF EXISTS t_file;

CREATE TABLE t_tinylog (id UInt64) ENGINE TinyLog() COMMENT 'TinyLog table';
CREATE TABLE t_stripelog (id UInt64) ENGINE StripeLog() COMMENT 'StripeLog table';
CREATE TABLE t_log (id UInt64) ENGINE Log() COMMENT 'Log table';
CREATE TABLE t_memory (id UInt64) ENGINE Memory() COMMENT 'Memory table';
CREATE TABLE t_set (id UInt64) ENGINE Set() COMMENT 'Set table';
CREATE TABLE t_join_log (id String) ENGINE Log();
CREATE TABLE t_join (id String) ENGINE Join(ANY, LEFT, id) COMMENT 'Join table';
CREATE TABLE t_buffer_log (id String) ENGINE Log();
CREATE TABLE t_buffer AS t_buffer_log ENGINE Buffer(default, t_buffer_log, 16, 10, 100, 10000, 1000000, 10000000, 100000000) COMMENT 'Buffer table';
CREATE TABLE t_merge_mt (id String) ENGINE MergeTree() ORDER BY id;
CREATE TABLE t_merge_log (id String) ENGINE Log();
CREATE TABLE t_merge as t_merge_mt ENGINE Merge(currentDatabase(), '^t_merge_') COMMENT 'Merge table';
CREATE TABLE t_null (id UInt64) ENGINE Null() COMMENT 'Null table';
CREATE TABLE t_url (id UInt64) ENGINE URL('http://127.0.0.1:12345/', CSV) COMMENT 'URL table';
CREATE TABLE t_generaterandom (id UInt64) ENGINE GenerateRandom(1, 5, 3) COMMENT 'GenerateRandom table';
CREATE TABLE t_jdbc (id Int32) ENGINE JDBC('jdbc:mysql://localhost:3306/?user=root&password=root', 'test', 'test') COMMENT 'JDBC table';
CREATE TABLE t_odbc (id Int32) ENGINE ODBC('DSN=mysqlconn', 'test', 'test') COMMENT 'ODBC table';
CREATE TABLE t_mongodb (id UInt32) ENGINE MongoDB('mongo1:27017', 'test', 'simple_table', 'testuser', 'clickhouse') COMMENT 'MongoDB table';
CREATE TABLE t_postgresql (id Int32) ENGINE PostgreSQL('localhost:5432', 'public', 'test', 'postges_user', 'postgres_password') COMMENT 'PostgreSQL table';
CREATE TABLE t_file (id UInt32) ENGINE File("CSV") COMMENT 'File table';

SHOW CREATE TABLE t_tinylog;
SELECT name, comment FROM system.tables WHERE name = 't_tinylog';
SHOW CREATE TABLE t_stripelog;
SELECT name, comment FROM system.tables WHERE name = 't_stripelog';
SHOW CREATE TABLE t_log;
SELECT name, comment FROM system.tables WHERE name = 't_log';
SHOW CREATE TABLE t_memory;
SELECT name, comment FROM system.tables WHERE name = 't_memory';
SHOW CREATE TABLE t_set;
SELECT name, comment FROM system.tables WHERE name = 't_set';
SHOW CREATE TABLE t_join;
SELECT name, comment FROM system.tables WHERE name = 't_join';
SHOW CREATE TABLE t_buffer;
SELECT name, comment FROM system.tables WHERE name = 't_buffer';
SHOW CREATE TABLE t_merge;
SELECT name, comment FROM system.tables WHERE name = 't_merge';
SHOW CREATE TABLE t_null;
SELECT name, comment FROM system.tables WHERE name = 't_null';
SHOW CREATE TABLE t_url;
SELECT name, comment FROM system.tables WHERE name = 't_url';
SHOW CREATE TABLE t_generaterandom;
SELECT name, comment FROM system.tables WHERE name = 't_generaterandom';
SHOW CREATE TABLE t_jdbc;
SELECT name, comment FROM system.tables WHERE name = 't_jdbc';
SHOW CREATE TABLE t_odbc;
SELECT name, comment FROM system.tables WHERE name = 't_odbc';
SHOW CREATE TABLE t_mongodb;
SELECT name, comment FROM system.tables WHERE name = 't_mongodb';
SHOW CREATE TABLE t_postgresql;
SELECT name, comment FROM system.tables WHERE name = 't_postgresql';
SHOW CREATE TABLE t_file;
SELECT name, comment FROM system.tables WHERE name = 't_file';

ALTER TABLE t_tinylog MODIFY COMMENT 'This is TinyLog table';
ALTER TABLE t_stripelog MODIFY COMMENT 'This is StripeLog table';
ALTER TABLE t_log MODIFY COMMENT 'This is Log table';
ALTER TABLE t_memory MODIFY COMMENT 'This is Memory table';
ALTER TABLE t_set MODIFY COMMENT 'This is Set table';
ALTER TABLE t_join MODIFY COMMENT 'This is Join table';
ALTER TABLE t_buffer MODIFY COMMENT 'This is Buffer table';
ALTER TABLE t_merge MODIFY COMMENT 'This is Merge table';
ALTER TABLE t_null MODIFY COMMENT 'This is Null table';
ALTER TABLE t_url MODIFY COMMENT 'This is URL table';
ALTER TABLE t_generaterandom MODIFY COMMENT 'This is GenerateRandom table';
ALTER TABLE t_jdbc MODIFY COMMENT 'This is JDBC table';
ALTER TABLE t_odbc MODIFY COMMENT 'This is ODBC table';
ALTER TABLE t_mongodb MODIFY COMMENT 'This is MongoDB table';
ALTER TABLE t_postgresql MODIFY COMMENT 'This is PostgreSQL table';
ALTER TABLE t_file MODIFY COMMENT 'This is File table';

SHOW CREATE TABLE t_tinylog;
SELECT name, comment FROM system.tables WHERE name = 't_tinylog';
SHOW CREATE TABLE t_stripelog;
SELECT name, comment FROM system.tables WHERE name = 't_stripelog';
SHOW CREATE TABLE t_log;
SELECT name, comment FROM system.tables WHERE name = 't_log';
SHOW CREATE TABLE t_memory;
SELECT name, comment FROM system.tables WHERE name = 't_memory';
SHOW CREATE TABLE t_set;
SELECT name, comment FROM system.tables WHERE name = 't_set';
SHOW CREATE TABLE t_join;
SELECT name, comment FROM system.tables WHERE name = 't_join';
SHOW CREATE TABLE t_buffer;
SELECT name, comment FROM system.tables WHERE name = 't_buffer';
SHOW CREATE TABLE t_merge;
SELECT name, comment FROM system.tables WHERE name = 't_merge';
SHOW CREATE TABLE t_null;
SELECT name, comment FROM system.tables WHERE name = 't_null';
SHOW CREATE TABLE t_url;
SELECT name, comment FROM system.tables WHERE name = 't_url';
SHOW CREATE TABLE t_generaterandom;
SELECT name, comment FROM system.tables WHERE name = 't_generaterandom';
SHOW CREATE TABLE t_jdbc;
SELECT name, comment FROM system.tables WHERE name = 't_jdbc';
SHOW CREATE TABLE t_odbc;
SELECT name, comment FROM system.tables WHERE name = 't_odbc';
SHOW CREATE TABLE t_mongodb;
SELECT name, comment FROM system.tables WHERE name = 't_mongodb';
SHOW CREATE TABLE t_postgresql;
SELECT name, comment FROM system.tables WHERE name = 't_postgresql';
SHOW CREATE TABLE t_file;
SELECT name, comment FROM system.tables WHERE name = 't_file';

DROP TABLE t_tinylog;
DROP TABLE t_stripelog;
DROP TABLE t_log;
DROP TABLE t_memory;
DROP TABLE t_set;
DROP TABLE t_join_log;
DROP TABLE t_join;
DROP TABLE t_buffer_log;
DROP TABLE t_buffer;
DROP TABLE t_merge_mt;
DROP TABLE t_merge_log;
DROP TABLE t_merge;
DROP TABLE t_null;
DROP TABLE t_url;
DROP TABLE t_generaterandom;
DROP TABLE t_jdbc;
DROP TABLE t_odbc;
DROP TABLE t_mongodb;
DROP TABLE t_postgresql;
DROP TABLE t_file;